default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "password") %>
  host: <%= ENV.fetch("DB_HOST", "127.0.0.1") %>  

development:
  <<: *default
  database: book_collection_development

test:
  <<: *default
  database: book_collection_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %> 