env:
  RUBY_VERSION: 3.2.2
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  DATABASE_USER: postgres
  DATABASE_PASSWORD: password

name: Rails tests

on: [push, pull_request]

jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Install postgres client
        run: sudo apt-get install -y libpq-dev

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Wait for Postgres
        run: |
          echo "Waiting for Postgres to be ready..."
          for i in {1..20}; do
            if PGPASSWORD=$POSTGRES_PASSWORD psql -h postgres -U $POSTGRES_USER -c '\l' > /dev/null 2>&1; then
              echo "Postgres is ready!"
              exit 0
            fi
            echo "Postgres not ready yet... retrying in 3s"
            sleep 3
          done
          echo "Postgres did not start in time"
          exit 1

      - name: Create database
        run: |
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test

      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Run tests
        run: bundle exec rspec .

      - name: Run brakeman
        run: brakeman -o brakeman.txt

      - name: Run rubocop
        run: bundle exec rubocop --force-exclusion vendor/*/** --out rubocop.txt

      - name: Upload coverage results
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: coverage-report
          path: coverage

      - name: Upload rubocop report
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: rubocop-report.txt
          path: rubocop.txt

      - name: Upload brakeman report
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: brakeman-report.txt
          path: brakeman.txt
