name: Rails tests

on: [push, pull_request]

env:
  RUBY_VERSION: 3.2.2
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password

jobs:
  rspec-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Install Postgres client
        run: sudo apt-get install -y libpq-dev

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Create database
        run: |
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test

      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Run tests
        run: bundle exec rspec

      - name: Run brakeman
        run: brakeman -o brakeman.txt --no-exit-on-warn

      - name: Run rubocop
        run: bundle exec rubocop --force-exclusion --out rubocop.txt

      - name: Upload coverage results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage-report
          path: coverage

      - name: Upload rubocop report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: rubocop-report.txt
          path: rubocop.txt

      - name: Upload brakeman report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: brakeman-report.txt
          path: brakeman.txt
