name: Rails CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    env:
      RAILS_ENV: test
      RUBY_VERSION: 2.7.6
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler: 2.3.26
          bundler-cache: true

      - name: Install Postgres client
        run: sudo apt-get install -y libpq-dev

      - name: Install dependencies
        run: |
          gem install bundler -v 2.3.26
          bundle install --jobs 4 --retry 3

      - name: Setup DB
        run: |
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test

      - name: Install Yarn
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Run tests
        run: bundle exec rspec --format documentation

      - name: Run Brakeman
        run: brakeman -o brakeman.txt

      - name: Run Rubocop
        run: bundle exec rubocop --force-exclusion vendor/*/** --out rubocop.txt

      - name: Upload coverage results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage-report
          path: coverage

      - name: Upload rubocop report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: rubocop-report.txt
          path: rubocop.txt

      - name: Upload brakeman report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: brakeman-report.txt
          path: brakeman.txt
