name: Rails tests

on: [push, pull_request]

jobs:
  rspec-test:
    runs-on: ubuntu-latest
    name: RSpec

    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      RUBY_VERSION: 3.2.2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      DB_HOST: postgres

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Install postgres client
        run: sudo apt-get install -y libpq-dev postgresql-client

      - name: Wait for Postgres
        run: |
          echo "Waiting for Postgres..."
          sleep 10
          PGPASSWORD=$POSTGRES_PASSWORD psql -h $DB_HOST -U $POSTGRES_USER -c '\l'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Setup DB
        run: |
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test

      - name: Run tests
        run: bundle exec rspec .

      - name: Run brakeman
        run: brakeman -o brakeman.txt

      - name: Run rubocop
        run: bundle exec rubocop --force-exclusion vendor/*/** --out rubocop.txt
